combine.all.data <- function(pdf.data, html.data, manual.data){

    ## combine.all.data appends the Williams College faculty
    ## dataframes generated by all three original sources of data -
    ## pdf, html, and manual data. Since the dataframes do not contain
    ## the exactly the same data, new columns with missing values are
    ## first added to the dataframes such that an rbind can be
    ## executed. combine.all.data returns a dataframe containing
    ## faculty data across all available academic years - 1965, 1975,
    ## 1985, 1995, and 1998-2010.

    ## Create vectors of NAs for missing columns in pdf data

    department <- rep(NA, times = nrow(pdf.data))
    area.of.study <- rep(NA, times = nrow(pdf.data))
    street.address <- rep(NA, times = nrow(pdf.data))
    town <- rep(NA, times = nrow(pdf.data))
    leave.info <- rep(NA, times = nrow(pdf.data))

    ## Create a dataframe consisting of the missing columns

    pdf.columns <- data.frame(department,
                              area.of.study,
                              street.address,
                              town,
                              leave.info)

    ## Add the missing columns to the pdf data

    pdf <- cbind(pdf.data, pdf.columns)

    ## Create vectors of NAs for missing columns in html data

    position <- rep(NA, times = nrow(html.data))
    undergrad.degree <- rep(NA, times = nrow(html.data))
    undergrad.school <- rep(NA, times = nrow(html.data))
    undergrad.year <- rep(NA, times = nrow(html.data))
    grad.degree <- rep(NA, times = nrow(html.data))
    grad.school <- rep(NA, times = nrow(html.data))
    grad.year <- rep(NA, times = nrow(html.data))
    area.of.study <- rep(NA, times = nrow(html.data))
    street.address <- rep(NA, times = nrow(html.data))
    town <- rep(NA, times = nrow(html.data))
    leave.info <- rep(NA, times = nrow(html.data))

    ## Create a dataframe consisting of the missing columns

    html.columns <- data.frame(position,
                               undergrad.degree,
                               undergrad.school,
                               undergrad.year,
                               grad.degree,
                               grad.school,
                               grad.year,
                               area.of.study,
                               street.address,
                               town,
                               leave.info)

    ## Add the missing columns to the pdf data

    html <- cbind(html.data, html.columns)

    ## Create vectors of NAs for missing columns in manual data

    title <- rep(NA, times = nrow(manual.data))
    department <- rep(NA, times = nrow(manual.data))

    ## Create a dataframe consisting of the missing columns

    manual.columns <- data.frame(title, department)

    ## Add the missing columns to the pdf data

    manual <- cbind(manual.data, manual.columns)

    ## Combine all datasets into one

    x <- rbind(pdf, html, manual)

    x$professor         <- as.character(x$professor)
    x$position          <- as.character(x$position)
    x$undergrad.school  <- as.character(x$undergrad.school)
    x$grad.school       <- as.character(x$grad.school)

    x$academic.year <- ordered(x$academic.year,
                                 levels = c(
                                 "1964-1965",
                                 "1974-1975",
                                 "1984-1985",
                                 "1994-1995",
                                 "1997-1998",
                                 "1998-1999",
                                 "1999-2000",
                                 "2000-2001",
                                 "2001-2002",
                                 "2002-2003",
                                 "2003-2004",
                                 "2004-2005",
                                 "2005-2006",
                                 "2006-2007",
                                 "2007-2008",
                                 "2008-2009",
                                 "2009-2010"))


    return(x)
}
