get.manual.data <- function(){

    ## get.manual.data reads in Williams College faculty data from a
    ## csv file that were generated by manually entering data from
    ## hard copies of Williams College course catalogs for academic
    ## years 1965, 1975, 1985, and 1995.

    require(williams)

    ## Establish the path and filename for the csv file

    filename <- system.file("faculty",
                       "manual data",
                       "Hard Copy Course Catalogs.csv",
                       package = "williams")

    ## Read in the raw data file

    x <- read.csv(filename)

    return(x)
}
